### ISSUE TITLE
week 02 - general font declaration

### ISSUE THREAD

**Issue by jakub-c** [chandu87/HYF-HTML-CSS#5]
https://github.com/chandu87/HYF-HTML-CSS/blob/8b09e559bb83de250e70168b6abc898a030b0ac5/week2/main.css#L2-L6

I think it's better to declare your fonts in the `<body>` if you would like to have a global font setting, `*` is an overkill

**Comment by chandu87** [comment]
ya got it.. thanks Jakub. I will declare fonts in body next time onwards.
